### ISSUE TITLE
Filter dead/experimental folders and modules from documentation

### ISSUE THREAD

**Issue by jurgenvinju** [cwi-swat/php-analysis#16]
This can be done with the `<ignores>` feature of the tutor in `pom.xml`

**Comment by mahills** [comment]
I'm in the process of pulling these out into their own projects -- we originally just put this stuff directly into PHP AiR, but I've been trying to change that so that PHP AiR only includes things that are generally useful, with separate projects then containing the code for specific experiments.

**Comment by jurgenvinju** [comment]
Ok. then perhaps it's better not to hide them in the API docs. Thanks for the heads up!
