### ISSUE TITLE
Link to Corpus broken

### ISSUE THREAD

**Issue by daniangelos** [cwi-swat/php-analysis#5]
Hi, 
I am starting to use your software, but in one of the firsts steps of the README file, I found out that the link you gave to the corpus systems is broken. Do you  #recommend just downloading the entire corpus?

**Comment by mahills** [comment]
The file is again available at that link. We're currently making some updates to include PHP 7 features, but everything should still work if you are analyzing code for PHP version 5 or below. 

Are there specific things you are trying to use the PHP analysis code for? I'm happy to help where I can.
